spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://34.47.68.184:5432/postgres?ssl=true&sslmode=require
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

jwt:
  secret: ${JWT_SECRET}
  access-token-expiry: 3600000       # 1시간 (ms)
  refresh-token-expiry: 2592000000   # 30일 (ms)

grpc:
  client:
    ai-server:
      address: static://34.50.58.227:50051
      negotiation-type: tls
      security:
        trust-cert-collection: file:/home/joha-eun/server.crt
        authority-override: semojum-ai